#!/usr/bin/env python3
"""
Spider Scaffolder - generate a ready-to-run Scrapling scraper or Spider project.

Standard library only. Produces a project directory with a runnable script,
requirements.txt, and a config file.

    python spider_scaffolder.py my_scraper --start-url 'https://example.com/' --mode spider
"""

import argparse
import json
import os
import re
import sys


def to_class_name(name: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", name)
    return "".join(p.capitalize() for p in parts if p) or "MyScraper"


SCRIPT_TEMPLATE = '''\
#!/usr/bin/env python3
"""Scrapling scraper generated by spider_scaffolder.py."""

import json

from scrapling.fetchers import {fetcher_import}

START_URL = "{start_url}"


def main():
    # Tier: {fetcher_name}. Escalate to StealthyFetcher/DynamicFetcher if this
    # returns a bot-challenge page or JS-only content (see fetcher_selection_guide.md).
    page = {fetch_call}

    items = []
    for element in page.css("{item_selector}", adaptive=True):
        items.append({{
            "text": element.css("::text").get(),
            # TODO: add fields, e.g. "href": element.css("a::attr(href)").get(),
        }})

    print(json.dumps(items, indent=2))


if __name__ == "__main__":
    main()
'''

SPIDER_TEMPLATE = '''\
#!/usr/bin/env python3
"""Scrapling Spider generated by spider_scaffolder.py."""

from scrapling.spiders import Spider, Request, Response


class {class_name}(Spider):
    name = "{name}"
    start_urls = ["{start_url}"]
    concurrent_requests = {concurrency}

    async def parse(self, response: Response):
        for element in response.css("{item_selector}"):
            yield {{
                "text": element.css("::text").get(),
                # TODO: add fields to extract
            }}

        # Follow pagination if present (adjust selector to the target site):
        next_page = response.css("a.next::attr(href)").get()
        if next_page:
            yield Request(response.urljoin(next_page), callback=self.parse)


if __name__ == "__main__":
    # crawldir enables pause/resume checkpoints for long crawls.
    {class_name}(crawldir="./crawl_data").start()
'''

REQUIREMENTS = "scrapling\n"

CONFIG_TEMPLATE = {
    "start_url": None,
    "fetcher": None,
    "item_selector": ".item",
    "adaptive": True,
    "concurrent_requests": 5,
    "respect_robots_txt": True,
    "rate_limit_seconds": 1.0,
}

FETCHER_MAP = {
    "fetch": ("Fetcher", "Fetcher.get(START_URL)", "Fetcher (HTTP)"),
    "stealthy": ("StealthyFetcher", "StealthyFetcher.fetch(START_URL, headless=True)", "StealthyFetcher (anti-bot)"),
    "dynamic": ("DynamicFetcher", "DynamicFetcher.fetch(START_URL, network_idle=True)", "DynamicFetcher (browser)"),
}


def main():
    parser = argparse.ArgumentParser(
        description="Scaffold a Scrapling scraper or Spider project")
    parser.add_argument("name", help="Project/scraper name (used for directory and class name)")
    parser.add_argument("--start-url", required=True, help="First URL to scrape")
    parser.add_argument("--mode", choices=["script", "spider"], default="script",
                         help="script = single-file scraper, spider = crawl framework")
    parser.add_argument("--fetcher", choices=["fetch", "stealthy", "dynamic"], default="fetch",
                         help="Fetcher tier for script mode")
    parser.add_argument("--item-selector", default=".item",
                         help="CSS selector for the repeated item to extract")
    parser.add_argument("--concurrency", type=int, default=5,
                         help="concurrent_requests for spider mode")
    parser.add_argument("--output-dir", help="Parent directory (default: current dir)")
    args = parser.parse_args()

    parent = args.output_dir or os.getcwd()
    project_dir = os.path.join(parent, args.name)
    if os.path.exists(project_dir):
        print(f"Error: {project_dir} already exists", file=sys.stderr)
        sys.exit(1)
    os.makedirs(project_dir)

    class_name = to_class_name(args.name)

    if args.mode == "spider":
        main_file = "spider.py"
        content = SPIDER_TEMPLATE.format(
            class_name=class_name,
            name=args.name,
            start_url=args.start_url,
            concurrency=args.concurrency,
            item_selector=args.item_selector,
        )
    else:
        main_file = "scraper.py"
        fetcher_import, fetch_call, fetcher_name = FETCHER_MAP[args.fetcher]
        content = SCRIPT_TEMPLATE.format(
            fetcher_import=fetcher_import,
            fetch_call=fetch_call,
            fetcher_name=fetcher_name,
            start_url=args.start_url,
            item_selector=args.item_selector,
        )

    with open(os.path.join(project_dir, main_file), "w", encoding="utf-8") as f:
        f.write(content)

    with open(os.path.join(project_dir, "requirements.txt"), "w", encoding="utf-8") as f:
        f.write(REQUIREMENTS)

    config = dict(CONFIG_TEMPLATE)
    config["start_url"] = args.start_url
    config["fetcher"] = args.fetcher
    config["item_selector"] = args.item_selector
    config["concurrent_requests"] = args.concurrency
    with open(os.path.join(project_dir, "config.json"), "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)

    print(f"Scaffolded {args.mode} project at {project_dir}/")
    print(f"  {main_file}")
    print("  requirements.txt")
    print("  config.json")
    print("\nNext steps:")
    print(f"  cd {project_dir}")
    print("  pip install -r requirements.txt")
    print("  pip install \"scrapling[fetchers]\" && scrapling install  # if using stealthy/dynamic")
    print(f"  python {main_file}")


if __name__ == "__main__":
    main()
